config/routes.rb
Rails.application.routes.draw do
  root "main#landing"
  post "/app", to: "main#app"
  get "/app", to: "main#app"
  delete "/remove_city", to: "main#remove_city"

  namespace :admin do
    get '/dashboard', to: "dashboard#index"
    resources :restaurants do
      resources :zones
    end
    resources :zones do
      resources :phones
    end
    resources :cities
    resources :specialities
  end

  get '/admin' => redirect('/admin/dashboard')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :zones
  validates :name, uniqueness: true
  has_many :restaurants, through: :zones
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :zone
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :image,:speciality, presence: true
  mount_uploader :image, ImageUploader
  has_many :zones
  belongs_to :speciality

  private
  def self.search_filter(speciality,zone,name)
    speciality = speciality.empty? ? " " : "%#{speciality}%"
    zone = zone.empty? ? " " : "%#{zone}%"
    name = name.empty? ? " " :  "%#{name}%"

    result = self.joins([:speciality,:zones]).where('restaurants.name ILIKE ? OR specialities.name ILIKE ? OR zones.address ILIKE ? ', name,speciality,zone)
  end

end

app/models/speciality.rb
class Speciality < ApplicationRecord
  has_many :restaurants
end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :restaurant
  belongs_to :city
  has_many :phones
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
end

app/controllers/admin/cities_controller.rb
class Admin::CitiesController < Admin::BaseController
  before_action :find_city, only: [:show,:edit,:update,:destroy]
  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new city_params
    if @city.save
      redirect_to admin_cities_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @city.update city_params
      redirect_to admin_cities_path
    else
      render 'edit'
    end
  end

  def destroy
    @city.destroy
    redirect_to admin_cities_path
  end
  private
    def city_params
      params.require(:city).permit(:name)
    end

    def find_city
      @city = City.find(params[:id])
    end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index

  end
end

app/controllers/admin/phones_controller.rb
class Admin::PhonesController < Admin::BaseController
  before_action :find_zone
  before_action :find_phone, only: [:edit,:show,:destroy,:update]
  def new
    @phone = Phone.new
  end
  def edit

  end
  def create
    @phone = Phone.new phone_params
    @phone.zone = @zone

    if @phone.save
      redirect_to admin_restaurant_zone_path(@zone.restaurant,@zone)
    else
      render 'new'
    end
  end

  def destroy
    @phone.destroy
    redirect_to admin_restaurant_zone_path(@zone.restaurant,@zone)
  end

  def update
    if @phone.update phone_params
      redirect_to admin_restaurant_zone_path(@zone.restaurant,@zone)
    else
      render 'edit'
    end
  end

  private
    def find_phone
      @phone = Phone.find(params[:id])
    end
    def find_zone
      @zone = Zone.find(params[:zone_id])
    end

    def phone_params
      params.require(:phone).permit(:number)
    end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  before_action :find_restaurant, only: [:edit, :show,:update,:destroy]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
    @specialities = Speciality.all
  end

  def create
    @restaurant = Restaurant.new restaurant_params
    if @restaurant.save
      redirect_to admin_restaurants_path
    else
      render 'new'
    end
  end

  def edit
    @specialities = Speciality.all

  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
  end

  def update
    if @restaurant.update restaurant_params
      redirect_to admin_restaurants_path
    else
      render 'edit'
    end
  end

  def show

  end

  private
   def restaurant_params
     params.require(:restaurant).permit(:name, :image, :stars, :speciality_id)
   end
   def find_restaurant
     @restaurant = Restaurant.find(params[:id])
   end
end

app/controllers/admin/specialities_controller.rb
class Admin::SpecialitiesController < Admin::BaseController
  before_action :find_speciality, only: [:show,:edit,:update,:destroy]
  def index
    @specialities = Speciality.all
  end

  def new
    @speciality = Speciality.new
  end

  def create
    @speciality = Speciality.new speciality_params
    if @speciality.save
      redirect_to admin_specialities_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @speciality.update speciality_params
      redirect_to admin_specialities_path
    else
      render 'edit'
    end
  end

  def destroy
    @speciality.destroy
    redirect_to admin_specialities_path
  end
  private
    def speciality_params
      params.require(:speciality).permit(:name)
    end

    def find_speciality
      @speciality = Speciality.find(params[:id])
    end
end

app/controllers/admin/zones_controller.rb
class Admin::ZonesController < Admin::BaseController
  before_action :find_restaurant
  before_action :find_zone, only: [:edit, :update,:destroy,:show]
  def new

    @zone = Zone.new
    @cities = City.all
  end

  def create
    @zone = Zone.new zone_params
    @zone.restaurant = @restaurant

    if @zone.save
      redirect_to admin_restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def edit
    @cities = City.all
  end

  def update
    if @zone.update zone_params
      redirect_to admin_restaurant_path(@restaurant)
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy
    @zone.destroy
    redirect_to admin_restaurant_path(@restaurant)
  end

  private
    def find_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def zone_params
      params.require(:zone).permit(:address,:schedule,:city_id)
    end

    def find_zone
      @zone = Zone.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :check_city_selected, only: [:landing]
  def landing
    @cities = City.all

  end

  #Method GET/POST
  def app
    if params[:city].nil?
      if session[:city].nil?
        redirect_to root_path
      else
        find_city
        app_content
      end
    else
      session[:city] = params[:city]
      find_city
      app_content
    end
  end

  #Method DELETE
  def remove_city
    session.delete(:city)
    redirect_to root_path
  end
  private
    def check_city_selected
      unless session[:city].nil?
        redirect_to app_path
      end
    end

    def find_city
      @city = City.find(session[:city])
      @string_welcome = "Te encuentras en: #{@city.name}"
    end

    def app_content
      permitted = params.permit(:speciality,:zone,:name)
      if permitted[:speciality].present? || permitted[:zone].present? || permitted[:name].present?
        speciality = permitted[:speciality]
        zone = permitted[:zone]
        name = permitted[:name]
        @restaurants = Kaminari.paginate_array(@city.restaurants.search_filter(speciality,zone,name).distinct).page(params[:page]).per(10)
      else
        @restaurants = Kaminari.paginate_array(@city.restaurants.distinct).page(params[:page]).per(10)

      end
    end

end

app/helpers/admin/cities_helper.rb
module Admin::CitiesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/phones_helper.rb
module Admin::PhonesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/admin/specialties_helper.rb
module Admin::SpecialtiesHelper
end

app/helpers/admin/zones_helper.rb
module Admin::ZonesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin/cities/_form.haml
= form_for [:admin, @city], class:"row s12" do |f|
  = render 'partials/admin/form_errors', object: @city
  .input-field
    = f.label :name, "Nombre"
    = f.text_field :name, placeholder: "Ingrese un nombre" , class: "form-control"
  .input-field
    =  f.submit "Guardar", class:"btn btn-primary indigo darken-3"

app/views/admin/cities/edit.haml
.row.mt-1
  .col-xs
    %h3
      Editar ciudad
    = render 'form'

app/views/admin/cities/index.haml
.row.mt-1
  .col-xs
    %h2
      Ciudades
    %table.table
      %thead.thead-default
        %tr
          %th
            Id
          %th
            Nombre
          %th
            Acciones
      %tbody
        - @cities.each do |city|
          %tr
            %td
              = city.id
            %td
              = city.name
            %td
              -# =link_to 'Ver',admin_city_path(city), class: "btn"
              =link_to 'Editar',edit_admin_city_path(city), class: "btn"
              =link_to 'Borrar',admin_city_path(city), class: "btn", method: :delete, data: {confirm: "Estas seguro?"}
.row.mt-1
  =link_to "Nueva ciudad",new_admin_city_path(), class: "btn indigo darken-3"

app/views/admin/cities/new.haml
.row.mt-1
  .col-xs
    %h3
      Nueva ciudad
    = render 'form'

app/views/admin/phones/_form.haml
= form_for [:admin, @zone, @phone], class:"row s12" do |f|
  = render 'partials/admin/form_errors', object: @phone
  .input-field
    = f.label :number, "Dirección"
    = f.text_field :number, placeholder: "Ingrese un numero de telefono" , class: "form-control"
  .input-field
    =  f.submit "Guardar", class:"btn btn-primary indigo darken-3"

app/views/admin/phones/edit.haml
.row.mt-1
  .col-xs
    %h3
      Editar Telefóno
    = render 'form'

app/views/admin/phones/new.haml
.row.mt-1
  .col-xs
    %h3
      Nuevo Telefóno
    = render 'form'

app/views/admin/restaurants/_form.haml
= form_for [:admin, @restaurant], multipart: true, class:"row s12" do |f|
  = render 'partials/admin/form_errors', object: @restaurant
  .input-field
    = f.label :name, "Nombre"
    = f.text_field :name, placeholder: "Ingrese su nombre" , class: "form-control"
  .input-field.file-field
    .btn.indigo.darken-3
      %span Imagen
      = f.file_field :image
    .file-path-wrapper
      %input{class: "file-path validate", type: "text"}
  .input-field
    = f.label :stars, "Estrellas"
    = f.number_field :stars, placeholder: "Numero de estrellas" , class: "form-control"
  .input-field
    = f.select :speciality_id, options_from_collection_for_select(@specialities, 'id', 'name'), prompt: "Selecciona una especialidad"
  .input-field
    =  f.submit "Guardar", class:"btn btn-primary indigo darken-3"

app/views/admin/restaurants/edit.haml
.row.mt-1
  .col-xs
    %h3
      Editar Restaurant
    = render 'form'

app/views/admin/restaurants/index.haml
.row.mt-1
  .col-xs
    %h2
      Restaurantes
    %table.table
      %thead.thead-default
        %tr
          %th
            Id
          %th
            Nombre
          %th
            Imagen
          %th
            Estrellas
          %th
            Zonas
          %th
            Acciones
      %tbody
        - @restaurants.each do |restaurant|
          %tr
            %td
              = restaurant.id
            %td
              = restaurant.name
            %td
              = image_tag restaurant.image.url, height: 120
            %td
              = restaurant.stars
            %td
              = restaurant.zones.count
            %td
              =link_to 'Ver',admin_restaurant_path(restaurant), class: "btn"
              =link_to 'Añadir Zonas',new_admin_restaurant_zone_path(restaurant), class: "btn"
              =link_to 'Editar',edit_admin_restaurant_path(restaurant), class: "btn"
              =link_to 'Borrar',admin_restaurant_path(restaurant), class: "btn", method: :delete, data: {confirm: "Estas seguro?"}
.row.mt-1
  =link_to "Nuevo Restaurante",new_admin_restaurant_path(), class: "btn indigo darken-3"

app/views/admin/restaurants/new.haml
.row.mt-1
  .col-xs
    %h3
      Nuevo Restaurant
    = render 'form'

app/views/admin/restaurants/show.haml
.row.mt-1
  .col-xs
    %h3
      = @restaurant.name
    %p
      %strong
        Estrellas:
      = @restaurant.stars
    = image_tag @restaurant.image.url, height: 250

  %p
  .row.mt-1
    .col-xs
      %h5
        Zonas
      %table.table
        %thead.thead-default
          %tr
            %th
              Id
            %th
              Dirección
            %th
              Horario
            %th
              Ciudad
            %th
              Acciones
        %tbody
          - @restaurant.zones.each do |zone|
            %tr
              %td
                = zone.id
              %td
                = zone.address
              %td
                = zone.schedule
              %td
                = zone.city.name
              %td
                =link_to 'Ver', admin_restaurant_zone_path(@restaurant,zone), class: "btn"
                =link_to 'Añadir Telefonos',new_admin_zone_phone_path(zone), class: "btn"
                =link_to 'Editar',edit_admin_restaurant_zone_path(@restaurant,zone), class: "btn"
                =link_to 'Borrar',admin_restaurant_zone_path(@restaurant,zone), class: "btn", method: :delete, data: {confirm: "Estas seguro?"}
      -# .text-xs-center
      -#   = paginate @posts
  .row.mt-1
    =link_to "Nueva Zona",new_admin_restaurant_zone_path(@restaurant), class: "btn indigo darken-3"

app/views/admin/zones/_form.haml
= form_for [:admin, @restaurant, @zone], class:"row s12" do |f|
  = render 'partials/admin/form_errors', object: @zone
  .input-field
    = f.label :address, "Dirección"
    = f.text_field :address, placeholder: "Ingrese una dirección" , class: "form-control"
  .input-field
    = f.label :schedule, "Horario"
    = f.text_field :schedule, placeholder: "Ingrese un horario" , class: "form-control"
  .input-field
    = f.select :city_id, options_from_collection_for_select(@cities, 'id', 'name'), prompt: "Selecciona una ciudad"
  .input-field
    =  f.submit "Guardar", class:"btn btn-primary indigo darken-3"

app/views/admin/zones/edit.haml
.row.mt-1
  .col-xs
    %h3
      Editar Zonas
    = render 'form'

app/views/admin/zones/new.haml
.row.mt-1
  .col-xs
    %h3
      Añadir Zonas
    = render 'form'

app/views/admin/zones/show.haml
.row.mt-1
  .col-xs
    %h3
      = @zone.restaurant.name
    %p
      %strong
        Dirección:
      = @zone.address
    %p
      %strong
        Horario de atención:
      = @zone.schedule
    %p
      %strong
        Ciudad:
      = @zone.city.name

  %br

  .row.mt-1
    .col-xs
      %h5
        Telefonos
      %table.table
        %thead.thead-default
          %tr
            %th
              Id
            %th
              Número
            %th
              Acciones
        %tbody
          - @zone.phones.each do |phone|
            %tr
              %td
                = phone.id
              %td
                = phone.number
              %td
                -# =link_to 'Ver', admin_restaurant_zone_path(@restaurant,zone), class: "btn"
                =link_to 'Editar',edit_admin_zone_phone_path(@zone,phone), class: "btn"
                =link_to 'Borrar',admin_zone_phone_path(@zone,phone), class: "btn", method: :delete, data: {confirm: "Estas seguro?"}
      -# .text-xs-center
      -#   = paginate @posts
  .row.mt-1
    =link_to "Nuevo Teléfono",new_admin_zone_phone_path(@zone), class: "btn indigo darken-3"