config/routes.rb
Rails.application.routes.draw do
  root "main#landing"
  post "/app", to: "main#app"
  get "/app", to: "main#app"
  delete "/remove_city", to: "main#remove_city"

  namespace :admin do
    get '/dashboard', to: "dashboard#index"
    resources :restaurants do
      resources :zones
    end
    resources :zones do
      resources :phones
    end
    resources :cities
    resources :specialities
  end

  get '/admin' => redirect('/admin/dashboard')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :zones
  validates :name, uniqueness: true
  has_many :restaurants, through: :zones
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :zone
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :image,:speciality, presence: true
  mount_uploader :image, ImageUploader
  has_many :zones
  belongs_to :speciality

  private
  def self.search_filter(speciality,zone,name)
    speciality = speciality.empty? ? " " : "%#{speciality}%"
    zone = zone.empty? ? " " : "%#{zone}%"
    name = name.empty? ? " " :  "%#{name}%"

    result = self.joins([:speciality,:zones]).where('restaurants.name ILIKE ? OR specialities.name ILIKE ? OR zones.address ILIKE ? ', name,speciality,zone)
  end

end

app/models/speciality.rb
class Speciality < ApplicationRecord
  has_many :restaurants
end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :restaurant
  belongs_to :city
  has_many :phones
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
end

app/controllers/admin/cities_controller.rb
class Admin::CitiesController < Admin::BaseController
  before_action :find_city, only: [:show,:edit,:update,:destroy]
  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new city_params
    if @city.save
      redirect_to admin_cities_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @city.update city_params
      redirect_to admin_cities_path
    else
      render 'edit'
    end
  end

  def destroy
    @city.destroy
    redirect_to admin_cities_path
  end
  private
    def city_params
      params.require(:city).permit(:name)
    end

    def find_city
      @city = City.find(params[:id])
    end

end

app/controllers/admin/phones_controller.rb
class Admin::PhonesController < Admin::BaseController
  before_action :find_zone
  before_action :find_phone, only: [:edit,:show,:destroy,:update]
  def new
    @phone = Phone.new
  end
  def edit

  end
  def create
    @phone = Phone.new phone_params
    @phone.zone = @zone

    if @phone.save
      redirect_to admin_restaurant_zone_path(@zone.restaurant,@zone)
    else
      render 'new'
    end
  end

  def destroy
    @phone.destroy
    redirect_to admin_restaurant_zone_path(@zone.restaurant,@zone)
  end

  def update
    if @phone.update phone_params
      redirect_to admin_restaurant_zone_path(@zone.restaurant,@zone)
    else
      render 'edit'
    end
  end

  private
    def find_phone
      @phone = Phone.find(params[:id])
    end
    def find_zone
      @zone = Zone.find(params[:zone_id])
    end

    def phone_params
      params.require(:phone).permit(:number)
    end

end

app/controllers/admin/zones_controller.rb
class Admin::ZonesController < Admin::BaseController
  before_action :find_restaurant
  before_action :find_zone, only: [:edit, :update,:destroy,:show]
  def new

    @zone = Zone.new
    @cities = City.all
  end

  def create
    @zone = Zone.new zone_params
    @zone.restaurant = @restaurant

    if @zone.save
      redirect_to admin_restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  def edit
    @cities = City.all
  end

  def update
    if @zone.update zone_params
      redirect_to admin_restaurant_path(@restaurant)
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy
    @zone.destroy
    redirect_to admin_restaurant_path(@restaurant)
  end

  private
    def find_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def zone_params
      params.require(:zone).permit(:address,:schedule,:city_id)
    end

    def find_zone
      @zone = Zone.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :check_city_selected, only: [:landing]
  def landing
    @cities = City.all

  end

  #Method GET/POST
  def app
    if params[:city].nil?
      if session[:city].nil?
        redirect_to root_path
      else
        find_city
        app_content
      end
    else
      session[:city] = params[:city]
      find_city
      app_content
    end
  end

  #Method DELETE
  def remove_city
    session.delete(:city)
    redirect_to root_path
  end
  private
    def check_city_selected
      unless session[:city].nil?
        redirect_to app_path
      end
    end

    def find_city
      @city = City.find(session[:city])
      @string_welcome = "Te encuentras en: #{@city.name}"
    end

    def app_content
      permitted = params.permit(:speciality,:zone,:name)
      if permitted[:speciality].present? || permitted[:zone].present? || permitted[:name].present?
        speciality = permitted[:speciality]
        zone = permitted[:zone]
        name = permitted[:name]
        @restaurants = Kaminari.paginate_array(@city.restaurants.search_filter(speciality,zone,name).distinct).page(params[:page]).per(10)
      else
        @restaurants = Kaminari.paginate_array(@city.restaurants.distinct).page(params[:page]).per(10)

      end
    end

end

app/helpers/admin/cities_helper.rb
module Admin::CitiesHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/phones_helper.rb
module Admin::PhonesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/admin/specialties_helper.rb
module Admin::SpecialtiesHelper
end

app/helpers/admin/zones_helper.rb
module Admin::ZonesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/admin.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SearchRestaurantRails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css",rel: "stylesheet"}

    / Font awesome

    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet"}
    / Compiled and minified CSS
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css", rel: "stylesheet"}
    / Compiled and minified JavaScript
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"}

    %link{href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet"}/


  %body
    = render 'partials/admin/nav'
    .container
      = yield
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"}

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SearchRestaurantRails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    / Font awesome

    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet"}
    / Compiled and minified CSS
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css", rel: "stylesheet"}
    / Compiled and minified JavaScript
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"}

    %link{href: "https://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet"}/


  %body
    = yield

app/views/partials/admin/_form_errors.haml
- if object.errors.any?
  %ul
    - object.errors.full_messages.each do |msg|
      %li
        = msg

app/views/partials/admin/_nav.haml
%nav.purple.darken-3
  .nav-wrapper.container
    = link_to "Admin", "/admin", class: "brand-logo"
    %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
      %i.material-icons menu
    %ul.right.hide-on-med-and-down
      %li
        = link_to "Restaurantes", admin_restaurants_path
      %li
        = link_to "Ciudades", admin_cities_path
      %li
        = link_to "Especialidades", admin_specialities_path
      %li
        = link_to "Ir a la app", root_path, class: "waves-effect waves-light btn indigo darken-3"
    %ul#mobile-demo.side-nav
      %li
        = link_to "Restaurantes", admin_restaurants_path
      %li
        = link_to "Ciudades", admin_cities_path
      %li
        = link_to "Especialidades", admin_specialities_path
      %li
        = link_to "Ir a la app", root_path

app/views/partials/app/_nav.haml
%nav.purple.darken-3
  .nav-wrapper.container
    %a.brand-logo{:href => "#!"} FoodSearch
    %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
      %i.material-icons menu
    %ul.right.hide-on-med-and-down
      %li
        = link_to "Cambiar ciudad", remove_city_path, class: "waves-effect waves-light btn indigo darken-3", method: :delete
    %ul#mobile-demo.side-nav
      %li
        = link_to "Cambiar ciudad", remove_city_path, method: :delete